export default {
  FETCH_EXCHANGES_URL: 'https://bitcoin-exchanges.firebaseio.com/exchanges.json',
  EXCHANGES_FETCH_STARTED: 'EXCHANGES_FETCH_STARTED',
  EXCHANGES_FETCHED: 'EXCHANGES_FETCHED',
  EXCHANGES_FETCH_FAILED: 'EXCHANGES_FETCH_FAILED',

  TICKER_FETCH_STARTED: 'TICKER_FETCH_STARTED',
  TICKER_FETCHED: 'TICKER_FETCHED',
  TICKER_FETCH_FAILED: 'TICKER_FETCH_FAILED',
}
